# Generated by Django 5.2.8 on 2025-11-29

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),  # Update this to your latest migration
    ]

    operations = [
        # Enable pgvector extension
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;'
        ),
        
        # Add vector fields to JobPosting
        migrations.AddField(
            model_name='jobposting',
            name='description_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        
        # Add vector fields to Candidate
        migrations.AddField(
            model_name='candidate',
            name='resume_text_cache',
            field=models.TextField(blank=True, help_text='Cached extracted resume text', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        
        # Add indexes for better query performance
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['-created_at'], name='recruitment_jobpost_created_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='recruitment_candida_created_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='recruitment_candida_email_idx'),
        ),
        
        # Create HNSW index for vector similarity search on candidates
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS recruitment_candidate_resume_embedding_idx 
            ON recruitment_candidate 
            USING hnsw (resume_embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="DROP INDEX IF EXISTS recruitment_candidate_resume_embedding_idx;"
        ),
        
        # Create HNSW index for vector similarity search on job postings
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS recruitment_jobposting_description_embedding_idx 
            ON recruitment_jobposting 
            USING hnsw (description_embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="DROP INDEX IF EXISTS recruitment_jobposting_description_embedding_idx;"
        ),
    ]
