# Generated by Django 5.2.8 on 2025-11-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_add_vector_embeddings"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="candidate",
            new_name="recruitment_created_a68753_idx",
            old_name="recruitment_candida_created_idx",
        ),
        migrations.RenameIndex(
            model_name="candidate",
            new_name="recruitment_email_9164c0_idx",
            old_name="recruitment_candida_email_idx",
        ),
        migrations.RenameIndex(
            model_name="jobposting",
            new_name="recruitment_created_c84675_idx",
            old_name="recruitment_jobpost_created_idx",
        ),
    ]
